pipeline {
    agent any

    tools { 
        go '1.21.1'
    }
    

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                git branch: 'main', url: 'https://github.com/ptisma/jenkins-agents.git'
            }
        }

        stage('List') {
            steps {
                // List contents of the workspace folder
                sh 'ls -l'
            }
        }
    
        stage('Build') {
            steps {
                dir('source-repo/') {
                    // Build the Go program
                    sh 'go build -o hello-world main.go'
                
            }
        }
        }

        stage('Test') {
            steps {
                dir('source-repo/') {
                // Run Go tests
                sh 'go test ./...'
                }
                
            }
        }

        stage('Retrieve Commit Tag') {
            steps {
                script {
                    // Retrieve the commit tag
                    def commitHash = sh(script: 'git rev-parse HEAD', returnStdout: true).trim()
                    
                    // Set the commit tag as an environment variable for later use
                    env.TAG = commitHash
                }
            }
        }

        stage('DockerLogin') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'DOCKER-CREDS', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                    // Log in to Docker registry
                    sh "echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin"
                }
            }
        }

        stage('DockerBuild') {
            steps {
                dir('source-repo/') {
                    script {
                        sh "docker build -t ptisma/hello-world-jenkins:${env.TAG} ."
                }
            }
            
            }
        }

        stage('DockerPush') {
            steps {
                dir('source-repo/') {
                    sh "docker push ptisma/hello-world-jenkins:${env.TAG}"
                }
                
            }
        }


    }

    post {
        success {
            echo 'Pipeline succeeded - Hello, World! Go program built successfully.'
        }
        failure {
            echo 'Pipeline failed - There might be issues with building or testing the Go program.'
        }
    }
}
