pipeline {
    agent any

    tools { 
        go '1.21.1'
        'org.jenkinsci.plugins.docker.commons.tools.DockerTool' '18.09' 
    }
    

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                git branch: 'main', url: 'https://github.com/ptisma/jenkins-agents.git'
            }
        }

        stage('List') {
            steps {
                // List contents of the workspace folder
                sh 'ls -l'
            }
        }
    
        stage('Build') {
            steps {
                dir('source-repo/') {
                    // Build the Go program
                    sh 'go build -o hello-world main.go'
                
            }
        }
        }

        stage('Test') {
            steps {
                dir('source-repo/') {
                // Run Go tests
                sh 'go test ./...'
                }
                
            }
        }

        stage('DockerBuild') {
            steps {
                dir('source-repo/') {
                // Run Go tests
                sh 'docker --version'
                }
                
            }
        }


    }

    post {
        success {
            echo 'Pipeline succeeded - Hello, World! Go program built successfully.'
        }
        failure {
            echo 'Pipeline failed - There might be issues with building or testing the Go program.'
        }
    }
}
