apiVersion: v1
kind: Pod
metadata:
  name: dind-sidecar
spec:
  containers:
  - name: dind
    image: docker:dind
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
    - name: DOCKER_TLS_VERIFY
      value: ""
    securityContext:
      privileged: true
  - name: alpine  
    image: alpine
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375 # localhost has to be here
    command: ["/bin/sh", "-c", "apk add --no-cache docker-cli git && git clone https://github.com/ptisma/jenkins-agents.git && /bin/sleep infinity"]

    
    